---
all:
  children:
    lb:
      hosts:
        cp-traefik:
          ansible_host: 10.1.0.100
        cp-authelia:
          ansible_host: 10.1.0.101
    data:
      hosts:
        cp-postgresql:
          ansible_host: 10.1.0.110
        cp-valkey:
          ansible_host: 10.1.0.111
    monitoring:
      hosts:
        cp-monitoring:
          ansible_host: 10.1.0.120
    cicd:
      hosts:
        cp-jenkins:
          ansible_host: 10.1.0.130
    app:
      hosts:
        cp-kopring:
          ansible_host: 10.1.0.140
