---
# Prometheus
prometheus_bin_dir: /opt/prometheus
prometheus_config_dir: /etc/prometheus
prometheus_data_dir: /var/lib/prometheus

# Grafana
grafana_home: /opt/grafana
grafana_config_dir: /etc/grafana
grafana_data_dir: /var/lib/grafana
grafana_log_dir: /var/log/grafana

# Loki
loki_bin_dir: /opt/loki
loki_config_dir: /etc/loki
loki_data_dir: /var/lib/loki

# Jaeger
jaeger_bin_dir: /opt/jaeger
jaeger_config_dir: /etc/jaeger
jaeger_data_dir: /var/lib/jaeger
