---
# Authelia 사용자 데이터베이스
# 플레이스홀더(__XXX__)는 deploy.sh에서 치환

users:
  cpadmin:
    disabled: false
    displayname: "CP Admin"
    email: "__CPADMIN_EMAIL__"
    groups:
      - "admins"
    password: "__CPADMIN_PASSWORD_HASH__"

  cpuser:
    disabled: false
    displayname: "CP User"
    email: "__CPUSER_EMAIL__"
    groups:
      - "users"
    password: "__CPUSER_PASSWORD_HASH__"
